# Run the previous test scripts as a prerequisite

# ADVANCE CLAP Embeddings Silhouette Score
rm advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_clap.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_clap_spectral_silhouette.csv

# ADVANCE Sentence Transformer Embeddings Silhouette Score
rm advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_st.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_st_spectral_silhouette.csv

# ADVANCE Alignment Vector Silhouette Score
rm advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> advance_cvector_spectral_silhouette.csv

# AHEAD-DS CLAP Embeddings Silhouette Score
rm ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_clap.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_clap_spectral_silhouette.csv

# AHEAD-DS Sentence Transformer Embeddings Silhouette Score
rm ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_st.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_st_spectral_silhouette.csv

# AHEAD-DS Alignment Vector Silhouette Score
rm ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> ahead-ds_cvector_spectral_silhouette.csv

# TAU2019 CLAP Embeddings Silhouette Score
rm tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_clap.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_clap_spectral_silhouette.csv

# TAU2019 Sentence Transformer Embeddings Silhouette Score
rm tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_st.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_st_spectral_silhouette.csv

# TAU2019 Alignment Vector Silhouette Score
rm tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=2 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=3 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=4 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=5 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=6 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=7 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=8 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=9 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=10 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=11 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=12 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=13 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=14 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=15 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=16 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=17 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=18 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=19 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=20 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=21 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=22 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=23 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=24 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=25 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=26 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=27 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=28 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=29 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=30 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=31 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=32 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=33 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=34 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=35 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=36 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=37 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=38 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=39 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=40 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=41 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=42 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=43 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=44 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=45 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=46 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=47 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=48 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=49 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=50 --label_csv=clustering_output.csv --png_plot=clustering_output.png >> tau2019_cvector_spectral_silhouette.csv

# Reproduce the clusters which are optimal
python3 cluster_spectral.py --cluster_npy=advance_cvector.npy --n_clusters=5 --label_csv=advance_optimal.csv --png_plot=advance_optimal.png
python3 cluster_spectral.py --cluster_npy=ahead-ds_cvector.npy --n_clusters=6 --label_csv=ahead-ds_optimal.csv --png_plot=ahead-ds_optimal.png
python3 cluster_spectral.py --cluster_npy=tau2019_cvector.npy --n_clusters=5 --label_csv=tau2019_optimal.csv --png_plot=tau2019_optimal.png

# Composite labels
python3 composite_label_stats.py --label_csv=advance_optimal.csv --top_label_scores_csv=advance_qwen2_5o_labels_scores.csv
python3 composite_label_stats.py --label_csv=ahead-ds_optimal.csv --top_label_scores_csv=ahead-ds_qwen2_5o_labels_scores.csv
python3 composite_label_stats.py --label_csv=tau2019_optimal.csv --top_label_scores_csv=tau2019_qwen2_5o_labels_scores.csv
